CREATE TABLE `b_awz_autform_codes` (
    ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    PHONE varchar(255) NOT NULL,
    CODE varchar(25) NOT NULL,
    IP_STR varchar(64) NOT NULL,
    CREATE_DATE timestamp,
    EXPIRED_DATE timestamp,
    PRM text,
    PRIMARY KEY (ID)
);
CREATE INDEX b_awz_autform_codes_ix_phone_date ON b_awz_autform_codes (PHONE, EXPIRED_DATE);
CREATE INDEX b_awz_autform_codes_ix_ip_str ON b_awz_autform_codes (IP_STR, EXPIRED_DATE);
CREATE INDEX b_awz_autform_codes_ix_expired_date ON b_awz_autform_codes (EXPIRED_DATE);
CREATE TABLE `b_awz_autform_logs` (
   ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   PHONE varchar(255) NOT NULL,
   CREATE_DATE timestamp,
   PRM text,
   PRIMARY KEY (ID)
);