<?
$moduleId = "awz.autform";
if(IsModuleInstalled($moduleId)) {
	$connection = \Bitrix\Main\Application::getConnection();
	if($connection->getType()=='mysql'){
$sql = "CREATE TABLE IF NOT EXISTS b_awz_autform_logs (
    ID int(18) NOT NULL AUTO_INCREMENT,
    PHONE varchar(255) NOT NULL,
    CREATE_DATE datetime NOT NULL,
    PRM longtext,
    PRIMARY KEY (ID)
);";
	}elseif($connection->getType()=='pgsql'){
$sql = "CREATE TABLE b_awz_autform_logs (
   ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   PHONE varchar(255) NOT NULL,
   CREATE_DATE timestamp,
   PRM text,
   PRIMARY KEY (ID)
)";
	}
	$connection->query($sql);
	CAgent::AddAgent(
	"\\Awz\\AutForm\\LogTable::clearOld();",
	$moduleId,
	"N",
	86400);
}